In [15]:
a=[10,20,30,40,50]
i=0
while i<len(a):
      print(a[i])
      i+=1

10
20
30
40
50

In [16]:
a=[1,2,3,4,5,6]
for x in a:
    print(x)

1
2
3
4
5
6

In [17]:
a=[9,8,7,6]
a.remove(6)
print(a)

[9, 8, 7]

In [18]:
a=[1,2,3,5]
a.pop()
print(a)

[1, 2, 3]

In [19]:
a=[200,300,400]
print(a.index(300))
print(a.index(400))
print(a.index(200))

1
2
0

In [20]:
a=[1,3,4,4,4,5,6]
set(a)

{1, 3, 4, 5, 6}

In [21]:
a=[2,4,3,7,9]
a.clear()
print(a)

[]

In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("GlobalWeatherRepository - GlobalWeatherRepository (1).csv")

In [24]:
df.iloc[5:10]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,05:36,18:32,13:05,01:14,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45,8.0,46.4,Clear,...,4.0,5.3,1,1,07:43,17:59,14:36,01:04,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,2024-05-16 12:45,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,05:45,20:12,13:17,02:31,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,2024-05-16 18:45,9.0,48.2,Clear,...,3.7,5.4,1,1,06:52,17:07,13:31,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,2024-05-16 10:45,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,05:14,20:29,13:00,02:42,Waxing Gibbous,55

In [25]:
import pandas as pd

In [26]:
df[df["latitude"]>10]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.1200,-61.8500,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.20,4.50,1,1,05:36,18:32,13:05,01:14,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135064,United States of America,Washington Harbor,48.0792,-123.0439,America/Los_Angeles,1775975400,2026-04-11 23:30,8.2,46.8,Partly cloudy,...,4.65,5.35,1,1,06:28,19:59,04:35,14:24,Waning Crescent,30
135066,Uzbekistan,Tashkent,41.3167,69.2500,Asia/Tashkent,1775975400,2026-04-12 11:30,22.4,72.3,Sunny,...,16.55,18.55,2,2,05:49,19:00,03:15,13:15,Waning Crescent,35
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34

In [27]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55

In [28]:
df.tail()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [29]:
df.sample(3)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
90266,Czech Republic,Prague,50.0833,14.4667,Europe/Prague,1756022400,2025-08-24 10:00,14.0,57.2,Sunny,...,7.955,13.690,1,1,06:05,20:03,07:15,20:29,Waxing Crescent,0
26819,Bulgaria,Bogot,43.3200,24.7000,Europe/Sofia,1727861400,2024-10-02 12:30,18.8,65.9,Sunny,...,10.730,14.615,1,1,07:20,19:00,06:50,18:51,New Moon,1
37466,Belize,Belmopan,17.2500,-88.7667,America/Belize,1732610700,2024-11-26 02:45,19.9,67.7,Fog,...,10.545,12.025,1,1,06:06,17:19,02:15,14:18,Waning Crescent,22

In [30]:
df.shape

(135073, 41)

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135073 entries, 0 to 135072
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       135073 non-null  object
 1   location_name                 135073 non-null  object
 2   latitude                      135073 non-null  float64
 3   longitude                     135073 non-null  float64
 4   timezone                      135073 non-null  object
 5   last_updated_epoch            135073 non-null  int64
 6   last_updated                  135073 non-null  object
 7   temperature_celsius           135073 non-null  float64
 8   temperature_fahrenheit        135073 non-null  float64
 9   condition_text                135073 non-null  object
 10  wind_mph                      135073 non-null  float64
 11  wind_kph                      135073 non-null  float64
 12  wind_degree                   135073 non-null  int64
 13  wind_direction                135073 non-null  object
 14  pressure_mb                   135073 non-null  int64
 15  pressure_in                   135073 non-null  float64
 16  precip_mm                     135073 non-null  float64
 17  precip_in                     135073 non-null  float64
 18  humidity                      135073 non-null  int64
 19  cloud                         135073 non-null  int64
 20  feels_like_celsius            135073 non-null  float64
 21  feels_like_fahrenheit         135073 non-null  float64
 22  visibility_km                 135073 non-null  float64
 23  visibility_miles              135073 non-null  int64
 24  uv_index                      135073 non-null  float64
 25  gust_mph                      135073 non-null  float64
 26  gust_kph                      135073 non-null  float64
 27  air_quality_Carbon_Monoxide   135073 non-null  float64
 28  air_quality_Ozone             135073 non-null  float64
 29  air_quality_Nitrogen_dioxide  135073 non-null  float64
 30  air_quality_Sulphur_dioxide   135073 non-null  float64
 31  air_quality_PM2.5             135073 non-null  float64
 32  air_quality_PM10              135073 non-null  float64
 33  air_quality_us-epa-index      135073 non-null  int64
 34  air_quality_gb-defra-index    135073 non-null  int64
 35  sunrise                       135073 non-null  object
 36  sunset                        135073 non-null  object
 37  moonrise                      135073 non-null  object
 38  moonset                       135073 non-null  object
 39  moon_phase                    135073 non-null  object
 40  moon_illumination             135073 non-null  int64
dtypes: float64(21), int64(9), object(11)
memory usage: 42.3+ MB

In [33]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [34]:
a=[6,3,9,1]
print(len(a))
print(max(a))
print(min(a))
print(sum(a))
print(sorted(a))

4
9
1
19
[1, 3, 6, 9]

In [35]:
a=[1,2,3]
a.reverse()
print(a)

[3, 2, 1]

In [36]:
e=[3,1,2]
print(sorted(e))

[1, 2, 3]

In [37]:
d=[10,20,30]
print(sum(d))

60

In [38]:
c=[5,2,8]
print(min(c))

2

In [39]:
b=[5,7,9]
print(max(b))

9

In [40]:
df[(df["latitude"]>10) & (df["latitude"]<50)]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.1200,-61.8500,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.20,4.50,1,1,05:36,18:32,13:05,01:14,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135064,United States of America,Washington Harbor,48.0792,-123.0439,America/Los_Angeles,1775975400,2026-04-11 23:30,8.2,46.8,Partly cloudy,...,4.65,5.35,1,1,06:28,19:59,04:35,14:24,Waning Crescent,30
135066,Uzbekistan,Tashkent,41.3167,69.2500,Asia/Tashkent,1775975400,2026-04-12 11:30,22.4,72.3,Sunny,...,16.55,18.55,2,2,05:49,19:00,03:15,13:15,Waning Crescent,35
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34

In [45]:
df[(df["latitude"]>10) | (df["latitude"]<50)]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.5200,69.1800,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.40,26.60,1,1,04:50,18:50,12:12,01:11,Waxing Gibbous,55
1,Albania,Tirana,41.3300,19.8200,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.10,2.00,1,1,05:21,19:54,12:58,02:14,Waxing Gibbous,55
2,Algeria,Algiers,36.7600,3.0500,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.40,18.40,1,1,05:40,19:50,13:15,02:14,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.5000,1.5200,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.70,0.90,1,1,06:31,21:11,14:12,03:31,Waxing Gibbous,55
4,Angola,Luanda,-8.8400,13.2300,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.40,262.30,5,10,06:12,17:55,13:17,00:38,Waxing Gibbous,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1775975400,2026-04-12 02:30,19.1,66.3,Partly Cloudy,...,16.35,18.15,2,2,06:18,18:38,02:36,14:31,Waning Crescent,31
135069,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1775975400,2026-04-12 13:30,34.2,93.6,Sunny,...,61.15,64.45,3,8,05:41,18:14,02:02,13:21,Waning Crescent,35
135070,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1775975400,2026-04-12 09:30,19.3,66.7,Sunny,...,7.45,15.35,1,1,05:51,18:17,02:06,13:45,Waning Crescent,34
135071,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1775975400,2026-04-12 08:30,18.5,65.3,Sunny,...,5.45,6.15,1,1,06:14,18:01,01:26,14:30,Waning Crescent,33
135072,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1775975400,2026-04-12 08:30,17.4,63.3,Sunny,...,19.85,20.55,2,2,06:04,17:49,01:10,14:22,Waning Crescent,33

In [42]:
a=[1,2,3]
print(len(a))

3

In [3]:
df[["longitude","latitude"]]=df["timezone"].str.split("/", expand = True)

NameError: name 'df' is not defined

In [ ]:
df["test1"]=df[]

SyntaxError: invalid syntax (3592981130.py, line 1)

In [51]:
df["latitude"].value_counts()

latitude
 41.90    833
 40.40    832
 12.15    830
 5.55     695
 3.75     695
         ...
 39.53      1
 4.60       1
 4.05       1
-4.05       1
 59.89      1
Name: count, Length: 397, dtype: int64

In [52]:
df["latitude"].mean()

np.float64(19.208948125087915)

In [53]:
df["longitude"].median()

23.2361

In [54]:
df["latitude"].max()

64.15

In [55]:
df["longitude"].min()

-175.2

In [56]:
df["latitude"].mode()

0    41.9
Name: latitude, dtype: float64

In [59]:
df[df["country"]=="India"]

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
77,India,New Delhi,28.6,77.2,Asia/Kolkata,1715849100,2024-05-16 14:15,42.0,107.6,Mist,...,25.40,64.00,2,3,05:30,19:06,12:47,01:30,Waxing Gibbous,55
272,India,New Delhi,28.6,77.2,Asia/Kolkata,1715868000,2024-05-16 19:30,38.0,100.4,Mist,...,44.00,80.80,3,5,05:30,19:06,12:47,01:30,Waxing Gibbous,55
467,India,New Delhi,28.6,77.2,Asia/Kolkata,1715961600,2024-05-17 21:30,36.0,96.8,Mist,...,49.70,83.70,3,6,05:30,19:06,13:40,01:58,Waxing Gibbous,64
659,India,New Delhi,28.6,77.2,Asia/Kolkata,1716042600,2024-05-18 20:00,41.0,105.8,Mist,...,32.50,58.70,2,3,05:29,19:07,14:32,02:24,Waxing Gibbous,73
853,India,New Delhi,28.6,77.2,Asia/Kolkata,1716128100,2024-05-19 19:45,41.0,105.8,Mist,...,31.70,55.00,2,3,05:28,19:08,15:24,02:51,Waxing Gibbous,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134175,India,New Delhi,28.6,77.2,Asia/Kolkata,1775629800,2026-04-08 12:00,24.2,75.6,Mist,...,35.75,69.75,2,3,06:04,18:43,No moonrise,09:49,Waning Gibbous,72
134370,India,New Delhi,28.6,77.2,Asia/Kolkata,1775716200,2026-04-09 12:00,27.3,81.1,Mist,...,66.05,106.05,4,9,06:03,18:43,00:37,10:43,Waning Gibbous,64
134565,India,New Delhi,28.6,77.2,Asia/Kolkata,1775803500,2026-04-10 12:15,29.2,84.6,Mist,...,85.65,419.95,4,10,06:01,18:44,01:24,11:40,Last Quarter,54
134760,India,New Delhi,28.6,77.2,Asia/Kolkata,1775889000,2026-04-11 12:00,31.4,88.5,Sunny,...,101.85,557.75,4,10,06:00,18:45,02:06,12:38,Waning Crescent,45
134955,India,New Delhi,28.6,77.2,Asia/Kolkata,1775975400,2026-04-12 12:00,31.1,88.0,Mist,...,70.05,222.55,4,9,05:59,18:45,02:43,13:38,Waning Crescent,35

In [60]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [61]:
df.isnull()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135068,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135069,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135070,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135071,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135072,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [63]:
df.shape

(135073, 41)

In [65]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [country, location_name, latitude, longitude, timezone, last_updated_epoch, last_updated, temperature_celsius, temperature_fahrenheit, condition_text, wind_mph, wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity, cloud, feels_like_celsius, feels_like_fahrenheit, visibility_km, visibility_miles, uv_index, gust_mph, gust_kph, air_quality_Carbon_Monoxide, air_quality_Ozone, air_quality_Nitrogen_dioxide, air_quality_Sulphur_dioxide, air_quality_PM2.5, air_quality_PM10, air_quality_us-epa-index, air_quality_gb-defra-index, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination]
Index: []

[0 rows x 41 columns]

In [66]:
df[df.duplicated()]

Empty DataFrame
Columns: [country, location_name, latitude, longitude, timezone, last_updated_epoch, last_updated, temperature_celsius, temperature_fahrenheit, condition_text, wind_mph, wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity, cloud, feels_like_celsius, feels_like_fahrenheit, visibility_km, visibility_miles, uv_index, gust_mph, gust_kph, air_quality_Carbon_Monoxide, air_quality_Ozone, air_quality_Nitrogen_dioxide, air_quality_Sulphur_dioxide, air_quality_PM2.5, air_quality_PM10, air_quality_us-epa-index, air_quality_gb-defra-index, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination]
Index: []

[0 rows x 41 columns]

In [69]:
df.sort_values(by="latitude")

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
101262,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1760859900,2025-10-19 20:45,14.1,57.4,Clear,...,7.250,10.050,1,1,06:26,19:47,05:16,17:32,Waning Crescent,9
12891,New Zealand,Wellington,-41.30,174.7800,Pacific/Auckland,1721479500,2024-07-21 00:45,10.4,50.7,Partly cloudy,...,0.900,1.500,1,1,07:40,17:16,15:27,06:48,Waxing Gibbous,97
24760,New Zealand,Wellington,-41.30,174.7800,Pacific/Auckland,1726915500,2024-09-21 22:45,12.3,54.1,Partly cloudy,...,5.735,10.545,1,1,06:12,18:16,22:20,07:34,Waning Gibbous,88
94439,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1757836800,2025-09-14 20:00,10.0,50.0,Partly cloudy,...,2.035,2.405,1,1,06:24,18:09,01:03,09:47,Last Quarter,61
115496,New Zealand,Wellington,-41.30,174.7833,Pacific/Auckland,1767164400,2025-12-31 20:00,16.2,61.2,Overcast,...,5.650,8.350,1,1,05:50,20:57,17:37,02:10,Waxing Gibbous,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128909,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1773297000,2026-03-12 06:30,-3.2,26.3,Clear,...,1.750,4.050,1,1,07:57,19:20,....,....,Waning Crescent,44
91663,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1756627200,2025-08-31 08:00,11.2,52.2,Sunny,...,7.215,9.435,1,1,06:08,20:46,00:00,00:00,First Quarter,47
131249,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1774333800,2026-03-24 06:30,-0.8,30.6,Light snow,...,2.150,4.250,1,1,07:15,19:56,****,****,Waxing Crescent,30
104334,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1762244100,2025-11-04 08:15,2.0,35.6,Clear,...,3.850,6.350,1,1,09:22,17:00,16:08,07:47,Waxing Gibbous,96
126942,Iceland,Reykjavik,64.15,-21.9500,Atlantic/Reykjavik,1772346600,2026-03-01 06:30,-4.0,24.8,Partly cloudy,...,4.750,6.850,1,1,08:35,18:46,15:37,08:56,Waxing Gibbous,93

In [72]:
df=df.drop_duplicates()

In [73]:
df=df.dropna(subset=["latitude"])

In [77]:
df["latitude"] =df["latitude"].fillna(0)

In [79]:
df["latitude"] =df["latitude"].fillna("")

In [81]:
df["latitude"]=df["latitude"].ffill()
df["latitude"]=df["latitude"].bfill()

In [87]:
df["country"].str.lower()

0         afghanistan
1             albania
2             algeria
3             andorra
4              angola
             ...
135068      venezuela
135069        vietnam
135070          yemen
135071         zambia
135072       zimbabwe
Name: country, Length: 135073, dtype: object

In [88]:
df["country"].str.upper()

0         AFGHANISTAN
1             ALBANIA
2             ALGERIA
3             ANDORRA
4              ANGOLA
             ...
135068      VENEZUELA
135069        VIETNAM
135070          YEMEN
135071         ZAMBIA
135072       ZIMBABWE
Name: country, Length: 135073, dtype: object